import React, { useState, useEffect, useRef } from 'react';
import * as Tone from 'tone';
import AudioEngine from '../utils/AudioEngine';

const Recorder = () => {
    const [isRecording, setIsRecording] = useState(false);
    const [isPlaying, setIsPlaying] = useState(false);
    const [recordedEvents, setRecordedEvents] = useState([]);

    const isRecordingRef = useRef(false);
    const startTimeRef = useRef(0);

    useEffect(() => {
        isRecordingRef.current = isRecording;
    }, [isRecording]);

    useEffect(() => {
        const unsubscribe = AudioEngine.subscribeToNotes((note) => {
            if (isRecordingRef.current && !isPlaying) { // Don't record notes generated by playback
                const time = Tone.now() - startTimeRef.current;
                setRecordedEvents(prev => [...prev, { note, time }]);
            }
        });
        return unsubscribe;
    }, [isPlaying]);

    const handleRecord = () => {
        setRecordedEvents([]);
        startTimeRef.current = Tone.now();
        setIsRecording(true);
    };

    const handleStop = () => {
        setIsRecording(false);
        setIsPlaying(false);
    };

    const handlePlay = () => {
        if (recordedEvents.length === 0) return;
        setIsPlaying(true);

        const now = Tone.now();
        // Schedule all notes
        recordedEvents.forEach(event => {
            // Buffer 0.1s to ensure we don't schedule in the past
            AudioEngine.playNote(event.note, "8n", now + event.time + 0.1);
        });

        // Reset playing state after last note
        const lastEvent = recordedEvents[recordedEvents.length - 1];
        // Assume last note lasts ~0.5s or so.
        const totalDuration = (lastEvent.time + 1.0) * 1000;

        setTimeout(() => {
            setIsPlaying(false);
        }, totalDuration);
    };

    return (
        <div className="recorder-container" style={{
            display: 'flex',
            gap: '1rem',
            padding: '1rem',
            background: 'rgba(0,0,0,0.3)',
            borderRadius: '15px',
            margin: '0.5rem 0',
            alignItems: 'center',
            justifyContent: 'center',
            border: '1px solid rgba(255,255,255,0.2)'
        }}>
            <button
                className="control-btn"
                style={{borderColor: '#ff4444', color: isRecording ? '#ff4444' : 'white'}}
                disabled={isRecording || isPlaying}
                onClick={handleRecord}
            >
                🔴 Record
            </button>
            <button
                className="control-btn"
                disabled={!isRecording && !isPlaying}
                onClick={handleStop}
            >
                ⏹ Stop
            </button>
            <button
                className="control-btn"
                style={{borderColor: '#44ff44', color: isPlaying ? '#44ff44' : 'white'}}
                disabled={isRecording || isPlaying || recordedEvents.length === 0}
                onClick={handlePlay}
            >
                ▶ Play
            </button>
            <div style={{color: 'white', marginLeft: '1rem', fontFamily: 'monospace'}}>
                {isRecording ? 'Recording...' : isPlaying ? 'Playing...' : `${recordedEvents.length} notes`}
            </div>
        </div>
    );
};

export default Recorder;
